### ISSUE TITLE
Log Rotate: Rotated file still in use

### ISSUE THREAD

**Issue by rayzilt** [elastic/logstash-forwarder#308]
It appears that logstash-forwarder keeps the rotated log files open.
1. Logrotate rotates log around 00:05 from access.log to access.log.1
2. We do some scripting around 00:30 against access.log.1
3. We move access.log.1 to a different location.
4. Logstash-forwarder crashes

/var/log/nginx is a NFS share. On a different server we mount this share for scripting purposes and also move the file away. This is the problem because the web-server doesn't know that the file is gone, and so logstash-forwarder either.

The question is: Why does logstash-forwarder keeps the rotated file open?

Version: HEAD~19812cf
OS: Debian 6.0.10
Linux 3.2.63-grsec #2 SMP Thu Oct 16 18:27:02 CEST 2014 x86_64 GNU/Linux

Debug information:

2014/11/07 00:05:13.895018 Launching harvester on rotated file: /var/log/nginx/access.log
2014/11/07 00:05:13.896337 harvest: "/var/log/nginx/access.log" (offset snapshot:0)
2014/11/07 00:05:14.168639 Registrar: precessing 1024 events
..........
2014/11/07 00:32:59.485583 Registrar: precessing 359 events
2014/11/07 00:33:04.090287 error: Harvester.readLine: read /var/log/nginx/access.log: no such file or directory
2014/11/07 00:33:04.090321 Unexpected state reading from /var/log/nginx/access.log; error: read /var/log/nginx/access.log: no such file or directory
panic: runtime error: invalid memory address or nil pointer dereference

goroutine 22 [running]:
runtime.panic(0x675cc0, 0x80cbb3)
    /usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
main.(_Harvester).Harvest(0xc2080041e0, 0xc20807c0e0)
    /root/downloads/logstash-forwarder/harvester.go:60 +0x529
created by main.(_Prospector).scan
    /root/downloads/logstash-forwarder/prospector.go:164 +0xe24

goroutine 16 [chan receive]:
main.Registrar(0xc20800f440, 0xc2080757a0)
    /root/downloads/logstash-forwarder/registrar.go:9 +0x79
main.main()
    /root/downloads/logstash-forwarder/logstash-forwarder.go:212 +0xde4

goroutine 19 [finalizer wait, 805 minutes]:
runtime.park(0x41fc60, 0x810e90, 0x80f929)
    /usr/local/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x810e90, 0x80f929)
    /usr/local/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
    /usr/local/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
    /usr/local/go/src/pkg/runtime/proc.c:1445

goroutine 20 [sleep]:
time.Sleep(0x2540be400)
    /usr/local/go/src/pkg/runtime/time.goc:39 +0x31
main.(*Prospector).Prospect(0xc208005c20, 0xc2080014c0, 0xc20807c0e0)
    /root/downloads/logstash-forwarder/prospector.go:67 +0x5e1
created by main.main
    /root/downloads/logstash-forwarder/logstash-forwarder.go:183 +0xb2d

goroutine 21 [sleep]:
time.Sleep(0x2540be400)
    /usr/local/go/src/pkg/runtime/time.goc:39 +0x31
main.(*Prospector).Prospect(0xc208005c80, 0xc2080014c0, 0xc20807c0e0)
    /root/downloads/logstash-forwarder/prospector.go:67 +0x5e1
created by main.main
    /root/downloads/logstash-forwarder/logstash-forwarder.go:183 +0xb2d

goroutine 23 [sleep]:
time.Sleep(0x3b9aca00)
    /usr/local/go/src/pkg/runtime/time.goc:39 +0x31
main.(_Harvester).readline(0xc208004300, 0xc208005da0, 0xc20803a0e0, 0x2540be400, 0x0, 0x0, 0x0, 0x0)
    /root/downloads/logstash-forwarder/harvester.go:152 +0x1d0
main.(_Harvester).Harvest(0xc208004300, 0xc20807c0e0)
    /root/downloads/logstash-forwarder/harvester.go:53 +0x476
created by main.(*Prospector).scan
    /root/downloads/logstash-forwarder/prospector.go:164 +0xe24

...............................

goroutine 305 [sleep]:
time.Sleep(0x3b9aca00)
    /usr/local/go/src/pkg/runtime/time.goc:39 +0x31
main.(_Harvester).readline(0xc208936ba0, 0xc208937440, 0xc2087ff5e0, 0x2540be400, 0x0, 0x0, 0x0, 0x0)
    /root/downloads/logstash-forwarder/harvester.go:152 +0x1d0
main.(_Harvester).Harvest(0xc208936ba0, 0xc20807c0e0)
    /root/downloads/logstash-forwarder/harvester.go:53 +0x476
created by main.(*Prospector).scan
    /root/downloads/logstash-forwarder/prospector.go:187 +0x13e9

**Comment by ymattw** [comment]
This issue still exists in the latest version, bigger problem is it causes number of opened files to accumulate continuously and will reach to the process limit (default is 1024) sooner or later.

**Comment by Deshke** [comment]
anything on this? i don't want to restart logstash-forwarder every 24 hours

**Comment by downeast** [comment]
In addition to setting a much shorter deadtime, try increasing the spool-size and harvest-buffer-size.  I have lsf running on many different servers and I only experienced this issue on the ones with the heaviest volume.  After some testing it seemed that lsf was legitimately still harvesting the file after it was rotated, and by increasing those settings and adding more indexers to receive the logs, the issue went away.

**Comment by ruflin** [comment]
The mentioned issues above should be fixed in the first release of filebeat (https://github.com/elastic/filebeat/) which should be available in the available in the next week. As @driskell mentioned above some of the issues can't be resolved as filebeat needs to keep the file open to make sure log lines are sent at least once.

@Deshke The reason you restart logstash-forwarder every 24 hours is because of the open files?

**Comment by Deshke** [comment]
yes, logstash kept the rotated file open(nginx-access.log -> nginx-access.log.$DATE) and did not reload it self to the new log (nginx-access.log)

**Comment by ruflin** [comment]
@Deshke What is your paths configuration? It could be that you have `*.log` and as a date is appended, the move file can't be found anymore so the file handle is never closed. The new generated log file is not picked up by logstash-forwarder?

**Comment by Deshke** [comment]
yes,  somewhere around that, happens on the syslog/authlog as on the nginx logs (part of my conf down below)




logstash-forwarder.conf
```yaml
....
"files": [
        {
            "paths": [
                "/var/log/syslog"
            ],
            "fields": {
                "type": "syslog"
            }
        },
        {
            "paths": [
                "/var/log/auth.log"
            ],
            "fields": {
                "type": "auth-log"
            }
        },
        {
            "paths": [
                "/var/log/nginx/*access.log"
            ],
            "fields": {
                "type": "nginx-access"
            }
        },.....
```

**Comment by ruflin** [comment]
What happens if you change 

```
            "paths": [
                "/var/log/nginx/*access.log"
            ],
```

to

```
            "paths": [
                "/var/log/nginx/*access.log.*"
            ],
```

Like this logstash should finish reading the moved file.

**Comment by fitz123** [comment]
Guys, what is the current recommended solution for logstash-forwarder log rotation?
Is it still daily restart?

**Comment by ruflin** [comment]
@fitz123 If it is about closing files after a certain time, ignore_older in filebeat is the current solution: https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-configuration-details.html#_ignore_older But related to this, also check issue https://github.com/elastic/filebeat/issues/181

**Comment by fitz123** [comment]
The question was about logstash-forwarder logs itself (/var/log/logstash-forwarder). Currently it continues log into rotated file (logstash-forwarder.err.1) and service restart is my workaround

But I get from your answer that forwarder is not supported anymore and current replacement is filebeat? Am I right?

Best Regards. A. L.

**Comment by ruflin** [comment]
@fitz123 Filebeat will be the next version of logstash-forwarder. It is planned to be GA in the next weeks and migrating to filebeat is recommended.

I thought you were referring to the log rotation of files lsf is reading. In filebeat, the log rotation is part of libbeat (the base library behind the beats) and will be done automatically (not restart required): Check here for more details: https://www.elastic.co/guide/en/beats/libbeat/current/configuration.html#_files_rotateeverybytes

**Comment by jordansissel** [comment]
> The question was about logstash-forwarder logs itself (/var/log/logstash-forwarder). Currently it continues log into rotated file (logstash-forwarder.err.1) and service restart is my workaround

There are two options I can see to workaround this at this time:

1) Use logrotate's copytruncate feature
2) or, use lsf's syslog logging option and have your syslog daemon and logrotate do the rotation.

**Comment by kpcool** [comment]
@ruflin 

You mentioned that filebeat will rotate the log file. I have a question about a configuration. Let's say Program A is writing logs to logFileA.log. 

We have configured, filebeat to consume logFileA.log and publish the changes to logstash. 

Now, will setting the files.rotateeverybytes value, rotate the logFileA.log? I think, it will not. If it will not, then what is the recommended way to rotate the logFileA.log. 

PS: I know we can use logrotate to handle this, but will the FileBeat then handle this properly without losing the logs between filebeat's last consumption and logrotate occuring?

**Comment by ruflin** [comment]
@kpcool I think you are confusing here two things:
* Filebeat rotating its own log files
* Reading rotated log files

Filebeat can do both. In case you use logrotate, filebeat is able to also read and follow the rotate files as is uses inode and device to identify files and not necessarly the file name.

**Comment by kpcool** [comment]
@ruflin Thanks for the clarification.
