### ISSUE TITLE
panic: runtime error: integer divide by zero on Debian wheezy 7.8

### ISSUE THREAD

**Issue by kalehrishi** [elastic/logstash-forwarder#446]
I was trying this tutorial on ec2 instance https://www.digitalocean.com/community/tutorials/how-to-install-elasticsearch-logstash-and-kibana-4-on-ubuntu-14-04

Came across this error. Could anyone let me know what is going wrong?

```log
2015/04/24 05:25:22.951754 Waiting for 1 prospectors to initialise
2015/04/24 05:25:22.951919 Launching harvester on new file: /var/log/syslog
2015/04/24 05:25:22.951953 Launching harvester on new file: /var/log/auth.log
2015/04/24 05:25:22.952087 harvest: "/var/log/syslog" (offset snapshot:0)
2015/04/24 05:25:22.952554 harvest: "/var/log/auth.log" (offset snapshot:0)
2015/04/24 05:25:22.952624 All prospectors initialised with 0 states to persist
2015/04/24 05:25:22.952820 Setting trusted CA from file: /etc/pki/tls/certs/logstash-forwarder.crt
panic: runtime error: integer divide by zero
[signal 0x8 code=0x1 addr=0x40b33c pc=0x40b33c]

goroutine 10 [running]:
main.connect(0xc208010150, 0xc20807a5b0)
        /home/jenkins/workspace/logstash-forwarder/publisher1.go:169 +0xa2c
main.Publishv1(0xc2080512c0, 0xc208051320, 0xc208010150)
        /home/jenkins/workspace/logstash-forwarder/publisher1.go:41 +0x96
created by main.main
        /home/jenkins/workspace/logstash-forwarder/logstash-forwarder.go:208 +0x1175

goroutine 1 [chan receive]:
main.Registrar(0xc20800b020, 0xc208051320)
        /home/jenkins/workspace/logstash-forwarder/registrar.go:9 +0x7d
main.main()
        /home/jenkins/workspace/logstash-forwarder/logstash-forwarder.go:211 +0x1195

goroutine 5 [sleep]:
main.(*Prospector).Prospect(0xc2080513e0, 0xc20802afc0, 0xc208051260)
        /home/jenkins/workspace/logstash-forwarder/prospector.go:67 +0x6c6
created by main.main
        /home/jenkins/workspace/logstash-forwarder/logstash-forwarder.go:182 +0xe26

goroutine 6 [runnable]:
main.(*Harvester).Harvest(0xc2080514a0, 0xc208051260)
        /home/jenkins/workspace/logstash-forwarder/harvester.go:89 +0xc2a
created by main.(*Prospector).scan
        /home/jenkins/workspace/logstash-forwarder/prospector.go:164 +0x1119

goroutine 7 [runnable]:
main.(*Harvester).Harvest(0xc208051500, 0xc208051260)
        /home/jenkins/workspace/logstash-forwarder/harvester.go:89 +0xc2a
created by main.(*Prospector).scan
        /home/jenkins/workspace/logstash-forwarder/prospector.go:164 +0x1119

goroutine 9 [select]:
main.Spool(0xc208051260, 0xc2080512c0, 0x400, 0x12a05f200)
        /home/jenkins/workspace/logstash-forwarder/spooler.go:26 +0x6c6
created by main.main
        /home/jenkins/workspace/logstash-forwarder/logstash-forwarder.go:206 +0x113e

```

**Comment by kalehrishi** [comment]
There was issue with config but it wasn't shown in error log.
