### ISSUE TITLE
stdin broken on windows

### ISSUE THREAD

**Issue by timove** [elastic/logstash-forwarder#522]
Setup:
- Windows 8.1
- logstash-forwarder 0.4.0
- minimal config file: network section forwards to local logstash, single file entry for stdin

When I start the logstash-forwarder it immediately throws an error.

```
2015/09/01 10:41:37.880034      --- options -------
2015/09/01 10:41:37.883036      config-arg:          logstash-forwarder-minimal.conf
2015/09/01 10:41:37.883036      idle-timeout:        5s
2015/09/01 10:41:37.883036      spool-size:          1024
2015/09/01 10:41:37.883036      harvester-buff-size: 16384
2015/09/01 10:41:37.883036      --- flags ---------
2015/09/01 10:41:37.883036      tail (on-rotation):  false
2015/09/01 10:41:37.883036      log-to-syslog:          false
2015/09/01 10:41:37.884036      quiet:             false
2015/09/01 10:41:37.884036 {
  "network": {
    "servers": [ "localhost:9999" ],
        "ssl ca": "C:\\Logging\\logstash-1.5.3\\etc\\cert.pem",
    "timeout": 15
  },

  "files": [
        {
      # A path of "-" means stdin.
      "paths": [ "-" ],
      "fields": { "type": "stdin" }
    }
  ]
}
2015/09/01 10:41:37.885037 Loading registrar data from C:\Logging\logstash-forwarder-0.4.0/.logstash-forwarder
2015/09/01 10:41:37.886037 Waiting for 1 prospectors to initialise
panic: Harvest: unexpected error: GetFileInformationByHandle /dev/stdin: Unzulässige Funktion.

goroutine 6 [running]:
main.(*Harvester).Harvest(0x122b2300, 0x122b3cc0)
        /home/jenkins/workspace/logstash-forwarder/harvester.go:25 +0x1b8
created by main.(*Prospector).Prospect
        /home/jenkins/workspace/logstash-forwarder/prospector.go:35 +0x199

goroutine 1 [runnable]:
main.main()
        /home/jenkins/workspace/logstash-forwarder/logstash-forwarder.go:191 +0xd10

goroutine 5 [sleep]:
main.(*Prospector).Prospect(0x122b22c0, 0x122d0550, 0x122b3cc0)
        /home/jenkins/workspace/logstash-forwarder/prospector.go:67 +0x5b6
created by main.main
        /home/jenkins/workspace/logstash-forwarder/logstash-forwarder.go:182 +0xbd1

goroutine 7 [runnable]:
runtime.timerproc()
        /home/jenkins/.gobrew/versions/1.4.1/src/runtime/time.go:151
runtime.goexit()
        /home/jenkins/.gobrew/versions/1.4.1/src/runtime/asm_386.s:2287 +0x1
```

**Comment by timove** [comment]
My mistake: When starting logstash-forwarder with this config from the console (cmd.exe) there simply is no stdin connected to the process -- unless explicitly specified. Hence the Stat() failed.
